### ISSUE TITLE
Think about active checks

### ISSUE THREAD

**Issue by GrayTShirt** [bolo/marco#2]
How a fact (ie: published - bound.port) generate a check on another machine. For instance a monitoring script is used to validate that a remote machine can contact the $bound.port

**Comment by geofffranks** [comment]
Should be fixed in v0.17.4?

**Comment by jhunt** [comment]
That's a spicy meat-a-ball-a!

**Comment by GrayTShirt** [comment]
latest public release is 0.17.4

**Comment by jhunt** [comment]
Can you link me to 0.10?

**Comment by geofffranks** [comment]
Looks like its only 0.1.0?

**Comment by GrayTShirt** [comment]
https://github.com/bolo/marco/releases
